=== IrinaTerlizhenko/EPAM/4_XML_Terlizhenko_Candies/resource/candies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="urn:xml.candies"
        xmlns:tns="urn:xml.candies"
        elementFormDefault="qualified">

    <element name="candy" type="tns:Candy"/>
    <element name="present_candy" type="tns:Present_candy" substitutionGroup="tns:candy"/>

	<element name="candies">
		<complexType>
			<sequence>
				<element ref="tns:candy" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Candy">
        <sequence>
            <element name="name">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[a-zA-Z][a-zA-Z0-9 ]*"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="energy" type="positiveInteger" />
            <element name="ingredient" type="tns:Ingredient" />
            <element name="value" type="tns:Value" />
            <element name="production">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[a-zA-Z][a-zA-Z0-9 ]*"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
        <attribute name="id" type="tns:Id" use="required" />
        <attribute name="type" default="caramel">
            <simpleType>
                <restriction base="string">
                    <enumeration value="caramel"></enumeration>
                    <enumeration value="iris"></enumeration>
                    <enumeration value="chocolate"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
	</complexType>

    <complexType name="Present_candy">
        <complexContent>
            <extension base="tns:Candy">
                <sequence>
                    <element name="packaging" type="tns:Packaging"/>
                    <element name="holiday" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="Id">
        <restriction base="ID">
            <pattern value="[A-Z]{3}([1-9]\d{3})((0[1-9])|(1[0-2]))((0[1-9])|([12]\d)|(3[01]))(([01]\d)|(2[0-3]))([0-5]\d){2}"/>
        </restriction>
    </simpleType>

    <complexType name="Packaging">
        <choice>
            <element name="color" type="string" />
            <element name="picture" type="string" />
        </choice>
        <attribute name="type" default="wrapper">
            <simpleType>
                <restriction base="string">
                    <enumeration value="wrapper"></enumeration>
                    <enumeration value="box"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

	<complexType name="Ingredient">
		<sequence>
			<element name="water" type="positiveInteger" />
			<element name="sugar" type="positiveInteger" />
			<element name="fructose" type="positiveInteger" />
			<element name="vanillin" type="positiveInteger" />
		</sequence>
	</complexType>

	<complexType name="Value">
		<sequence>
			<element name="proteins" type="positiveInteger" />
			<element name="fats" type="positiveInteger" />
			<element name="carbohydrates" type="positiveInteger" />
		</sequence>
	</complexType>

</schema>

=== IrinaTerlizhenko/EPAM/4_XML_Terlizhenko_Candies/resource/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="urn:xml.candies"
          xsi:schemaLocation="urn:xml.candies candies.xsd">

	<candy id="BLR20160403100917" type="chocolate">
		<name>Krolik</name>
		<energy>90</energy>
		<ingredient>
			<water>10</water>
			<sugar>15</sugar>
			<fructose>6</fructose>
			<vanillin>11</vanillin>
		</ingredient>
		<value>
			<proteins>4</proteins>
			<fats>9</fats>
			<carbohydrates>12</carbohydrates>
		</value>
		<production>Company A</production>
	</candy>

    <candy id="BLR20160403103125" type="chocolate">
        <name>Mishka</name>
        <energy>90</energy>
        <ingredient>
            <water>10</water>
            <sugar>15</sugar>
            <fructose>6</fructose>
            <vanillin>11</vanillin>
        </ingredient>
        <value>
            <proteins>4</proteins>
            <fats>9</fats>
            <carbohydrates>12</carbohydrates>
        </value>
        <production>Company A</production>
    </candy>

    <present_candy id="USA20160403142437" type="caramel">
        <name>Santa</name>
        <energy>90</energy>
        <ingredient>
            <water>10</water>
            <sugar>15</sugar>
            <fructose>6</fructose>
            <vanillin>11</vanillin>
        </ingredient>
        <value>
            <proteins>4</proteins>
            <fats>9</fats>
            <carbohydrates>12</carbohydrates>
        </value>
        <production>Candy Production Inc</production>
        <packaging type="wrapper">
            <color>Blue</color>
        </packaging>
        <holiday>New Year</holiday>
    </present_candy>

    <present_candy id="ITA20151230235207" type="iris">
        <name>Santa</name>
        <energy>90</energy>
        <ingredient>
            <water>10</water>
            <sugar>15</sugar>
            <fructose>6</fructose>
            <vanillin>11</vanillin>
        </ingredient>
        <value>
            <proteins>4</proteins>
            <fats>9</fats>
            <carbohydrates>12</carbohydrates>
        </value>
        <production>Company B</production>
        <packaging type="box">
            <picture>Santa Claus</picture>
        </packaging>
        <holiday>New Year</holiday>
    </present_candy>

</candies>
